// Design tokens from the Stitch "Atelier Dark" export (design/stitch/atelier_dark/DESIGN.md).
// Kept identical to the Stitch config so the pages render exactly like the screens.
module.exports = {
  content: ["./src/**/*.{astro,html,js,ts,md,mdx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        outline: "#8c928e",
        "outline-variant": "#424844",
        primary: "#b3ccbf",
        "on-primary": "#1e352b",
        "primary-container": "#8fa89b",
        "on-primary-container": "#273d33",
        "primary-fixed": "#cee9da",
        "primary-fixed-dim": "#b3ccbf",
        secondary: "#b7cdad",
        "on-secondary": "#23351e",
        "secondary-container": "#394c33",
        "on-secondary-container": "#a6bb9c",
        "secondary-fixed": "#d3e9c8",
        "secondary-fixed-dim": "#b7cdad",
        tertiary: "#afcdc0",
        "on-tertiary": "#1a352c",
        "tertiary-container": "#8ba99c",
        "on-tertiary-container": "#233e34",
        surface: "#111317",
        "surface-dim": "#111317",
        "surface-bright": "#37393d",
        "surface-container-lowest": "#0c0e11",
        "surface-container-low": "#1a1c1f",
        "surface-container": "#1e2023",
        "surface-container-high": "#282a2d",
        "surface-container-highest": "#333538",
        "surface-variant": "#333538",
        "on-surface": "#e2e2e6",
        "on-surface-variant": "#c2c8c3",
        background: "#111317",
        "on-background": "#e2e2e6",
        error: "#ffb4ab",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        "space-2xl": "4rem",
        "space-3xl": "7rem",
        gutter: "1.5rem",
        "gutter-desktop": "2.5rem",
        margin: "1.25rem",
        "margin-tablet": "3rem",
        "margin-desktop": "5rem",
      },
      fontFamily: {
        display: ["Plus Jakarta Sans"],
        "display-mobile": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "headline-sm": ["Plus Jakarta Sans"],
        "title-md": ["Plus Jakarta Sans"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "body-sm": ["Inter"],
        "label-md": ["Inter"],
        "label-caps": ["Space Grotesk"],
        "code-sm": ["Space Grotesk"],
      },
      fontSize: {
        display: ["4.5rem", { lineHeight: "1.05", letterSpacing: "-0.03em", fontWeight: "600" }],
        "display-mobile": ["2.75rem", { lineHeight: "1.1", letterSpacing: "-0.025em", fontWeight: "600" }],
        "headline-lg": ["3rem", { lineHeight: "1.15", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg-mobile": ["2rem", { lineHeight: "1.2", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-md": ["2rem", { lineHeight: "1.25", letterSpacing: "-0.015em", fontWeight: "500" }],
        "headline-sm": ["1.5rem", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "500" }],
        "title-md": ["1.125rem", { lineHeight: "1.4", letterSpacing: "-0.005em", fontWeight: "500" }],
        "body-lg": ["1.125rem", { lineHeight: "1.65", letterSpacing: "-0.01em", fontWeight: "400" }],
        "body-md": ["1rem", { lineHeight: "1.6", letterSpacing: "-0.005em", fontWeight: "400" }],
        "body-sm": ["0.875rem", { lineHeight: "1.5", letterSpacing: "0", fontWeight: "400" }],
        "label-md": ["0.875rem", { lineHeight: "1.2", letterSpacing: "0", fontWeight: "500" }],
        "label-caps": ["0.75rem", { lineHeight: "1", letterSpacing: "0.12em", fontWeight: "600" }],
        "code-sm": ["0.8125rem", { lineHeight: "1.4", letterSpacing: "0.02em", fontWeight: "400" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};
